// <auto-generated />
namespace DoradcaWyjazdowWypoczynkowych.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Init3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init3));
        
        string IMigrationMetadata.Id
        {
            get { return "201406081503060_Init3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
